code4romania/rezultate-vot-api

src/ElectionResults.API/Configuration/AWSS3Settings.cs, src/ElectionResults.API/Controllers/HomeController.cs, src/ElectionResults.API/ElectionResults.API.csproj, src/ElectionResults.API/Startup.cs, src/ElectionResults.API/appsettings.json
Closes #1 
Changed number of uploaded pics
Added s3 bucket upload
=> #1 added s3 bucket upload

src/ElectionResults.API/Views/Home/Index.cshtml
Closes #2
Adds hours minutes seconds
=> added hours minutes seconds

src/ElectionResults.Core/Repositories/ArticleRepository.cs
Closes #7 
Adds re-ordering for newsfeed by timestamp descending
=> #7 added re-ordered by timestamp descending

src/ElectionResults.API/Controllers/HomeController.cs
=> fixes aws link

src/ElectionResults.API/Controllers/HomeController.cs
=> fixed build

src/ElectionResults.API/Controllers/BallotsController.cs, src/ElectionResults.Core/Elections/ResultsAggregator.cs
- filter news just on the election level - not on ballot level.
Closes #XXX
=> use just electionId for news filter

src/ElectionResults.API/Controllers/BallotsController.cs
=> fix build issue caused by tiny typo

src/ElectionResults.API/appsettings.Development.json, src/ElectionResults.API/appsettings.json, src/ElectionResults.Core/ElectionResults.Core.csproj, src/ElectionResults.Core/Elections/IResultsAggregator.cs, src/ElectionResults.Core/Elections/ResultsAggregator.cs, src/ElectionResults.Core/Elections/ResultsProcessor.cs, src/ElectionResults.Core/Elections/WinnersAggregator.cs, src/ElectionResults.Core/Endpoints/Response/CandidateResponse.cs, src/ElectionResults.Core/Extensions/NameProcessingExtensions.cs, src/ElectionResults.Core/Extensions/StringExtensions.cs, src/ElectionResults.Core/Infrastructure/Consts.cs, src/ElectionResults.Core/Scheduler/CsvDownloaderJob.cs, src/ElectionResults.Core/Scheduler/JsonCandidateModel.cs, src/ElectionResults.Core/Scheduler/JsonResultsModel.cs, src/ElectionResults.Core/Scheduler/ScheduledProcessor.cs
Closes #XXX 
Local and staging env
=> Store candidates in db

src/ElectionResults.Core/Elections/ResultsAggregator.cs
=> Fixed turnout

src/ElectionResults.Core/Elections/ResultsAggregator.cs
=> Show capital city results when using "Mayor" ballot

src/ElectionResults.API/Startup.cs
=> Import results on startup

src/ElectionResults.Core/Elections/ResultsAggregator.cs
=> Fixed results for sectors

src/ElectionResults.API/Controllers/BallotsController.cs, src/ElectionResults.Core/Elections/ResultsAggregator.cs, src/ElectionResults.Core/Elections/WinnersAggregator.cs, src/ElectionResults.Core/Repositories/ITerritoryRepository.cs, src/ElectionResults.Core/Repositories/TerritoryRepository.cs
=> Filter localities

src/ElectionResults.Core/Elections/WinnersAggregator.cs
Closes #XXX 
Local and on the test server
=> Sent locality id in locality winners

src/ElectionResults.API/Startup.cs, src/ElectionResults.Core/Endpoints/Response/BallotType.cs, src/ElectionResults.Core/Extensions/StringExtensions.cs
Fixed snake_case bug
Closes #XXX 
Local and on test env
=> Fixed snake_case for enums

src/ElectionResults.Core/Elections/WinnersAggregator.cs
=> Fixed 500 error response for winner map

.github/workflows/build-prod.yml, .github/workflows/build-stage.yml, deploy/restart.sh
=> Update the deployment with automation

deploy/restart.sh
Update restart script to remove `sudo`
=> Update restart script

src/ElectionResults.Core/Elections/ResultsAggregator.cs
=> Aggregate turnouts for diaspora

src/ElectionResults.Core/Elections/WinnersAggregator.cs
Closes #101 
Included the Election object when retrieving ballots from the database
Local
=> Included Election in query for ballot

src/ElectionResults.Core/Elections/ResultsAggregator.cs, src/ElectionResults.Core/Endpoints/Response/ElectionResponse.cs, src/ElectionResults.Core/Scheduler/CsvDownloaderJob.cs
Closes #91
Adds a flag for aggregated results.
Local
=> Added flag for aggregated results

.github/workflows/build-prod.yml, .github/workflows/build-stage.yml
Update script location for automatic deployments.
=> Update script location

src/ElectionResults.API/Startup.cs, src/ElectionResults.Core/Elections/ResultsAggregator.cs, src/ElectionResults.Core/Elections/WinnersAggregator.cs
Added mayor and local council winners for national division
Local
=> Winners for national division

src/ElectionResults.Core/Elections/WinnersAggregator.cs
Fixed national winners results
Local
=> Fixed results for national winners

src/ElectionResults.API/Controllers/BallotsController.cs, src/ElectionResults.API/ElectionResults.API.csproj, src/ElectionResults.API/Startup.cs, src/ElectionResults.Core/Elections/IResultsAggregator.cs, src/ElectionResults.Core/Elections/ResultsAggregator.cs, src/ElectionResults.Core/Endpoints/Response/BasicCandidateInfo.cs, src/ElectionResults.Core/Endpoints/Response/CandidateResponse.cs, src/ElectionResults.Core/Endpoints/Response/PartyList.cs, src/ElectionResults.Core/Extensions/BallotExtensions.cs, src/ElectionResults.Core/Infrastructure/Consts.cs, src/ElectionResults.Core/Repositories/TerritoryRepository.cs, src/ElectionResults.Importer/ElectionResults.Importer.csproj, src/ElectionResults.Importer/ExcelCandidate.cs, src/ElectionResults.Importer/ParliamentImporter.cs, src/ElectionResultsApi.sln
Imported candidates for the 2020 Parliament elections
Created endpoint for retrieving the candidates
Local and dev server
=> Import 2020 parliament candidates

src/ElectionResults.API/Startup.cs
=> Moved import

src/ElectionResults.API/Startup.cs, src/ElectionResults.Importer/ParliamentImporter.cs
Added a timeout for the import task
Local
=> Added a timeout for the import task

src/ElectionResults.API/Import/ParliamentCrawler.cs, src/ElectionResults.API/Startup.cs, src/ElectionResults.API/appsettings.json, src/ElectionResults.Core/Scheduler/IParliamentCrawler.cs, src/ElectionResults.Core/Scheduler/ScheduleTask.cs
Used background service for importing candidates
Local
=> Used background service for importing candidates

src/ElectionResults.API/Import/ParliamentCrawler.cs, src/ElectionResults.API/Startup.cs, src/ElectionResults.Core/Infrastructure/Log.cs, src/ElectionResults.Importer/ParliamentImporter.cs
Added more logs for the import job
=> Added more logs for the import job

src/ElectionResults.API/Import/TurnoutCrawler.cs
=> Fixed build error

src/ElectionResults.API/Import/TurnoutCrawler.cs, src/ElectionResults.API/Startup.cs, src/ElectionResults.API/appsettings.Development.json, src/ElectionResults.API/appsettings.json, src/ElectionResults.Core/Configuration/LiveElectionSettings.cs, src/ElectionResults.Core/Elections/LiveElectionUrlBuilder.cs, src/ElectionResults.Core/Elections/ResultsAggregator.cs, src/ElectionResults.Core/Elections/ResultsProcessor.cs, src/ElectionResults.Core/Extensions/NameProcessingExtensions.cs, src/ElectionResults.Core/Infrastructure/FileDownloader.cs, src/ElectionResults.Core/Infrastructure/IFileDownloader.cs, src/ElectionResults.Core/Scheduler/IResultsCrawler.cs, src/ElectionResults.Core/Scheduler/ResultsCrawler.cs
Implemented parliament results crawler.
Local
=> Implemented results crawler

src/ElectionResults.API/appsettings.Development.json, src/ElectionResults.API/appsettings.json, src/ElectionResults.Core/Elections/LiveElectionUrlBuilder.cs, src/ElectionResults.Core/Elections/ResultsAggregator.cs
Fixed crash on results endpoint when the url could not be created
Local
=> Fixed crash on results endpoint

src/ElectionResults.Core/Elections/ResultsAggregator.cs, src/ElectionResults.Core/Elections/ResultsProcessor.cs
Send defaults if there are no results
Local
=> Send defaults if there are no results

src/ElectionResults.API/Import/TurnoutCrawler.cs
Mapped country names with values from the database
Local
=> Mapped country names with values from the database

src/ElectionResults.API/Import/TurnoutCrawler.cs, src/ElectionResults.API/appsettings.json
Replaced the count instead of adding new entry in the database
Local
=> Updated the votes for diaspora instead of adding a new entry

src/ElectionResults.Core/Elections/ResultsAggregator.cs
Set diaspora eligible voters equal with total votes
Local
=> Set diaspora eligible voters equal with total votes

src/ElectionResults.API/ElectionResults.API.csproj, src/ElectionResults.API/libman.json, src/ElectionResults.Core/Elections/ResultsAggregator.cs
Enabled library restore from CDN at build time and fixed minorities query
Local
=> Admin improvements

src/ElectionResults.API/Controllers/BallotsController.cs, src/ElectionResults.Core/Elections/WinnersAggregator.cs, src/ElectionResults.Core/Repositories/ITerritoryRepository.cs, src/ElectionResults.Core/Repositories/TerritoryRepository.cs
Returns only countries that have votes
Local
=> Return only countries that have votes

src/ElectionResults.Core/Elections/ResultsAggregator.cs
Fixed turnout for diaspora in past elections
Fixed a crash when there were no results for a specific location
Local
=> Diaspora turnout fix

src/ElectionResults.API/Controllers/BallotsController.cs, src/ElectionResults.API/Import/TurnoutCrawler.cs, src/ElectionResults.Core/Repositories/MemoryCache.cs
Synced results for national and diaspora
Local
=> Synced national and diaspora voters count

src/ElectionResults.API/Controllers/BallotsController.cs, src/ElectionResults.API/Import/TurnoutCrawler.cs, src/ElectionResults.Core/Repositories/MemoryCache.cs
Synced complete turnout object
Local
=> Synced complete turnout for national and diaspora

src/ElectionResults.API/Controllers/BallotsController.cs, src/ElectionResults.API/Import/TurnoutCrawler.cs, src/ElectionResults.Core/Repositories/MemoryCache.cs
Merge develop to master branch.
=> Merge develop to master

src/ElectionResults.API/Controllers/BallotsController.cs
=> Updated eligible voters

src/ElectionResults.API/Controllers/BallotsController.cs
=> Removed sync from diaspora and national

src/ElectionResults.API/Import/TurnoutCrawler.cs, src/ElectionResults.API/appsettings.Development.json, src/ElectionResults.API/appsettings.json, src/ElectionResults.Core/Configuration/LiveElectionSettings.cs, src/ElectionResults.Core/Elections/LiveElectionUrlBuilder.cs, src/ElectionResults.Core/Elections/ResultsAggregator.cs, src/ElectionResults.Core/Extensions/StringExtensions.cs, src/ElectionResults.Core/Scheduler/CsvDownloaderJob.cs, src/ElectionResults.Core/Scheduler/IResultsCrawler.cs, src/ElectionResults.Core/Scheduler/ResultsCrawler.cs
=> Aggregated national results

src/ElectionResults.Core/Elections/ResultsAggregator.cs, src/ElectionResults.Core/Elections/ResultsProcessor.cs, src/ElectionResults.Core/Endpoints/Response/ElectionResultsResponse.cs, src/ElectionResults.Core/Scheduler/ResultsCrawler.cs
=> Aggregate national results

src/ElectionResults.Core/Elections/ResultsAggregator.cs, src/ElectionResults.Core/Infrastructure/Consts.cs, src/ElectionResults.Core/Scheduler/IResultsCrawler.cs, src/ElectionResults.Core/Scheduler/ResultsCrawler.cs
=> Imported capital city results

src/ElectionResults.API/appsettings.Development.json, src/ElectionResults.Core/Elections/ILiveElectionUrlBuilder.cs, src/ElectionResults.Core/Elections/LiveElectionUrlBuilder.cs, src/ElectionResults.Core/Elections/ResultsAggregator.cs, src/ElectionResults.Core/Scheduler/IResultsCrawler.cs, src/ElectionResults.Core/Scheduler/ResultsCrawler.cs
=> Diaspora results

src/ElectionResults.Core/Elections/ResultsAggregator.cs, src/ElectionResults.Core/Scheduler/IResultsCrawler.cs, src/ElectionResults.Core/Scheduler/ResultsCrawler.cs
Implemented results per country
=> Implemented results per country

src/ElectionResults.API/Import/TurnoutCrawler.cs, src/ElectionResults.Core/Elections/ResultsAggregator.cs, src/ElectionResults.Core/Scheduler/IResultsCrawler.cs, src/ElectionResults.Core/Scheduler/ResultsCrawler.cs
=> Added results for sectors

src/ElectionResults.API/Import/TurnoutCrawler.cs, src/ElectionResults.Core/Elections/ResultsAggregator.cs, src/ElectionResults.Core/Scheduler/IResultsCrawler.cs, src/ElectionResults.Core/Scheduler/ResultsCrawler.cs
Merge develop branch to master
=> Merge develop branch to master

src/ElectionResults.Core/Elections/ResultsAggregator.cs, src/ElectionResults.Core/Scheduler/ResultsCrawler.cs
=> Fixed null and counted votes

src/ElectionResults.Core/Elections/ResultsAggregator.cs, src/ElectionResults.Core/Scheduler/CsvIndexes.cs, src/ElectionResults.Core/Scheduler/CsvMode.cs, src/ElectionResults.Core/Scheduler/IResultsCrawler.cs, src/ElectionResults.Core/Scheduler/ResultsCrawler.cs
Map votes to columns instead of indexes
=> Map votes to columns instead of indexes

src/ElectionResults.Core/Scheduler/ResultsCrawler.cs
=> Added white votes to null

src/ElectionResults.API/Import/TurnoutCrawler.cs, src/ElectionResults.Core/Elections/ResultsAggregator.cs, src/ElectionResults.Core/Scheduler/CsvIndexes.cs, src/ElectionResults.Core/Scheduler/CsvMode.cs, src/ElectionResults.Core/Scheduler/IResultsCrawler.cs, src/ElectionResults.Core/Scheduler/ResultsCrawler.cs
Merge develop to master branch
=> Merge develop to master branch

src/ElectionResults.Core/Scheduler/ResultsCrawler.cs
Added correspondence results for individual countries
=> Added correspondence results for individual countries

src/ElectionResults.Core/Elections/LiveElectionUrlBuilder.cs, src/ElectionResults.Core/Elections/ResultsAggregator.cs, src/ElectionResults.Core/Extensions/AsyncEx.cs, src/ElectionResults.Core/Infrastructure/FileDownloader.cs, src/ElectionResults.Core/Scheduler/IResultsCrawler.cs, src/ElectionResults.Core/Scheduler/ResultsCrawler.cs, src/ElectionResults.Core/Scheduler/ScheduledTask.cs
Import final parliament results
=> Import final parliament results

src/docker-compose.yml
=> Add CPU limit and always restart

terraform/cloudfront.tf
Remove caching on /Identity path
=> Cache Policy

src/ElectionResults.API/Controllers/BallotsController.cs, src/ElectionResults.API/ElectionResults.API.csproj, src/ElectionResults.API/Startup.cs, src/ElectionResults.Core/ElectionResults.Core.csproj, src/ElectionResults.Core/Elections/WinnersAggregator.cs, src/ElectionResults.Core/Repositories/BallotsRepository.cs, src/ElectionResults.Core/Repositories/ElectionsRepository.cs, src/ElectionResults.Core/Repositories/MemoryCache.cs, src/ElectionResults.Core/Repositories/PartiesRepository.cs, src/ElectionResults.Core/Repositories/TerritoryRepository.cs
=> Brought back memory cache for elections older than 2024
